FROM postgres:11

RUN apt-get update \
    && apt-get install -y wget python3 python3-psycopg2 python3-tz python3-numpy python3-netcdf4 postgresql-11-postgis-2.5 python3-pip \
    && pip3 install xarray \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /windb2
COPY / /windb2/
